services:
  postgres:
    image: "postgres:alpine"
    ports:
      - 15432:5432
    env_file:
      - .env
    networks:
      - postgres-network

  bot:
    build: .
    env_file:
      - .env
    networks:
      - postgres-network
    depends_on:
      - postgres

networks:
  postgres-network:
    driver: bridge